import { Question } from 'data/content/assessment/question';
import guid from 'utils/guid';
import { MultipleChoice } from 'data/content/assessment/multiple_choice';
import { responsesMatchAnswerChoices, testScores } from './_questions-test';
const jsonCheckAllThatApply = require('./questions-valid/cata.json');

// tslint:disable max-line-length
describe('check all that apply should be parsed correctly', () => {
  // test both toPersistence and fromPersistence
  const question: Question = Question.fromPersistence(
    Question.fromPersistence(jsonCheckAllThatApply, guid()).toPersistence(),
    guid());

  const items = question.items;
  const item = items.first() as MultipleChoice;

  const choices = item.choices;

  const parts = question.parts;
  const part = parts.first();

  const responses = part.responses;

  it('has one item', () => {
    expect(items.size).toEqual(1);
    expect(item.contentType).toBe('MultipleChoice');
  });

  it('is check all that apply and not multiple choice', () => {
    expect(item.select).toEqual('multiple');
  });

  it('has 4 choices', () => {
    expect(choices.size).toEqual(4);
  });

  it('has one part', () => {
    expect(parts.size).toEqual(1);
  });

  it('has autogenerated responses', () => {
    expect(responses.size).toEqual(15);
  });

  it('does not remove responses that dont match up to answer choices, eg autogen responses, * matches, and targeted feedback', () => {
    const values = choices.toArray().map(choice => choice.value);
    const matches = responses.toArray().map(response => response.match);

    expect(responsesMatchAnswerChoices(values, matches)).toBeFalsy();
  });

  testScores(responses);
});
