// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Jss = require("styles/jss");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var NumericMatchOptionsStyle = require("./NumericMatchOptions.style");

var componentName = "NumericMatchOptions";

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent(componentName);

function make(className, classes, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var match = classes[componentName];
      var componentClass = match !== undefined ? match : "";
      return React.createElement("div", {
                  className: Jss.classNames(/* :: */[
                        componentName,
                        /* :: */[
                          componentClass,
                          /* :: */[
                            className,
                            /* [] */0
                          ]
                        ]
                      ])
                }, children);
    });
  return newrecord;
}

var jsComponentUnstyled = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.className, jsProps.classes, jsProps.children);
      }));

var jsComponent = Jss.injectSheetRE(NumericMatchOptionsStyle.styles, jsComponentUnstyled);

exports.componentName = componentName;
exports.str = str;
exports.component = component;
exports.make = make;
exports.jsComponentUnstyled = jsComponentUnstyled;
exports.jsComponent = jsComponent;
/* component Not a pure module */
