import * as React from 'react';
import * as Immutable from 'immutable';
import * as contentTypes from 'data/contentTypes';
import { AppContext } from 'editors/common/AppContext';
import { StyledComponentProps } from 'types/component';
import { injectSheet, classNames, JSSProps } from 'styles/jss';
import { ToolbarButton, ToolbarButtonSize } from 'components/toolbar/ToolbarButton';
import { buildUrl } from 'utils/path';
import { RectangleEditor } from './RectangleEditor';

import { styles } from './ImageHotspotEditor.styles';
import { Hotspot } from 'data/content/assessment/image_hotspot/hotspot';
import guid from 'utils/guid';
import { Maybe } from 'tsmonad';

const mapCoordsToCircleProps = (coords: Immutable.List<number>) => {
  return {
    cx: coords.get(0),
    cy: coords.get(1),
    r: coords.get(2),
  };
};

const mapCoordsToPolygonProps = (coords: Immutable.List<number>) => {
  return {
    points: coords.join(','),
  };
};

export interface ImageHotspotEditorProps {
  className?: string;
  editMode: boolean;
  model: contentTypes.ImageHotspot;
  partModel: contentTypes.Part;
  context: AppContext;
  onEdit: (model: contentTypes.ImageHotspot, partModel: contentTypes.Part, src?: Object) => void;
}

export interface ImageHotspotEditorState {
  selectedHotspot: Maybe<string>;
}

/**
 * ImageHotspotEditor React Component
 */
@injectSheet(styles)
export class ImageHotspotEditor
    extends React.PureComponent<StyledComponentProps<ImageHotspotEditorProps>,
    ImageHotspotEditorState> {
  ref: any;

  constructor(props) {
    super(props);

    this.state = {
      selectedHotspot: Maybe.nothing(),
    };

    this.setRef = this.setRef.bind(this);
    this.handleOutsideClick = this.handleOutsideClick.bind(this);
    this.onEditCoords = this.onEditCoords.bind(this);
    this.onSelectHotspot = this.onSelectHotspot.bind(this);
    this.onAddHotspot = this.onAddHotspot.bind(this);
    this.onRemoveHotspot = this.onRemoveHotspot.bind(this);
  }

  componentDidMount() {
    window.addEventListener('click', this.handleOutsideClick);
  }

  componentWillUnmount() {
    window.removeEventListener('click', this.handleOutsideClick);
  }

  handleOutsideClick(e) {
    if (this.ref && !this.ref.contains(e.target)) {
      // click was not generated by image hotspot editor
      this.onSelectHotspot(Maybe.nothing());
    }
  }

  setRef(ref) {
    this.ref = ref;
  }

  onEditCoords(guid: string, coords: Immutable.List<number>) {
    const { model, partModel, onEdit } = this.props;

    onEdit(
      model.with({
        hotspots: model.hotspots.set(
          guid,
          model.hotspots.get(guid).with({ coords }),
        ),
      }),
      partModel,
    );
  }

  onSelectHotspot(guid: Maybe<string>) {
    this.setState({
      selectedHotspot: guid,
    });
  }

  onAddHotspot(shape: string) {
    const { model, partModel, onEdit } = this.props;

    // create new hotspot
    const match = guid();
    let newHotspot = new Hotspot({
      shape,
      value: match,
    });

    // set default coordinates depending on the shape type
    switch (shape) {
      // case 'poly':
      //   break;
      // case 'circle':
      //   break;
      case 'rect':
      default:
        newHotspot = newHotspot.with({
          coords: Immutable.List<number>([
            Math.floor(model.width / 2) - 50,
            Math.floor(model.height / 2) - 50,
            Math.floor(model.width / 2) + 50,
            Math.floor(model.height / 2) + 50,
          ]),
        });
        break;
    }

    // create corresponding response feedback
    const feedback = contentTypes.Feedback.fromText('', guid());
    let response = new contentTypes.Response();
    response = response.with({
      match,
      input: partModel.responses.size > 0
        ? partModel.responses.first().input
        : guid(),
      feedback: response.feedback.set(feedback.guid, feedback),
    });
    const updatedPartModel = partModel.with(
      { responses: partModel.responses.set(response.guid, response) });

    // add new hotspot to the model
    onEdit(
      model.with({
        hotspots: model.hotspots.set(
          newHotspot.guid,
          newHotspot,
        ),
      }),
      updatedPartModel,
    );

    // select the new hotspot
    this.setState({
      selectedHotspot: Maybe.just(newHotspot.guid),
    });
  }

  onRemoveHotspot(guid: string) {
    const { model, partModel, onEdit } = this.props;

    onEdit(
      model.with({
        hotspots: model.hotspots.remove(guid),
      }),
      partModel.with({
        responses: partModel.responses
          .filter(r => r.match !== model.hotspots.get(guid).value)
          .toOrderedMap(),
      }),
    );

    // deselect deleted hotspot
    this.setState({
      selectedHotspot: Maybe.nothing<string>(),
    });
  }

  render() {
    const { className, classes, editMode, context, model } = this.props;
    const { selectedHotspot } = this.state;

    return (
      <div
        className={classNames(['ImageHotspotEditor', classes.ImageHotspotEditor, className])}
        ref={this.setRef}
        style={{ width: model.width && model.width + 2 }}>
        <div className={classes.toolbar}>
        <ToolbarButton
            onClick={() => { console.log('NOT IMPLEMENTED'); }}
            size={ToolbarButtonSize.Small}
            tooltip="Select Hotspot Image"
            disabled={!editMode}>
          <i className="fa fa-picture-o" />
        </ToolbarButton>
        <ToolbarButton
            onClick={() => this.onAddHotspot('rect')}
            size={ToolbarButtonSize.Fit}
            tooltip="Create a rectangle hotspot"
            disabled={!editMode}>
          Rectangle
        </ToolbarButton>
        <ToolbarButton
            onClick={() => { console.log('NOT IMPLEMENTED'); }}
            size={ToolbarButtonSize.Fit}
            tooltip="Create a circle hotspot"
            disabled={!editMode}>
          Circle
        </ToolbarButton>
        <ToolbarButton
            onClick={() => { console.log('NOT IMPLEMENTED'); }}
            size={ToolbarButtonSize.Fit}
            tooltip="Create a polygon hotspot"
            disabled={!editMode}>
          Polygon
        </ToolbarButton>
        <div className="flex-spacer" />
        <ToolbarButton
            onClick={() => this.onRemoveHotspot(selectedHotspot.valueOr(''))}
            size={ToolbarButtonSize.Fit}
            className={classes.removeHotspotButton}
            tooltip="Remove selected hotspot"
            disabled={selectedHotspot.caseOf({ just: () => false, nothing: () => true })}>
          Remove Hotspot
        </ToolbarButton>
        </div>
        <div
          className={classes.imageBody}
          onMouseDown={e => this.onSelectHotspot(Maybe.nothing())}>
          {model.src
            ? (
              <div className={classes.hotspotBody}>
                <img
                  src={buildUrl(
                    context.baseUrl,
                    context.courseId,
                    context.resourcePath,
                    model.src,
                  )}
                  width={model.width} height={model.height} />
                <svg className={classes.hotspots} width={model.width} height={model.height}>
                  {model.hotspots.sort(h => h.guid === selectedHotspot.valueOr('') ? 1 : 0)
                    .toArray()
                    .map((hotspot) => {
                      switch (hotspot.shape) {
                        case 'rect':
                          return (
                            <RectangleEditor
                              key={hotspot.guid}
                              id={hotspot.guid}
                              selected={hotspot.guid === selectedHotspot.valueOr('')}
                              coords={hotspot.coords}
                              onSelect={this.onSelectHotspot}
                              onEdit={coords => this.onEditCoords(hotspot.guid, coords)} />
                          );
                        case 'circle':
                          return (
                            <circle
                              key={hotspot.guid}
                              className={classes.hotspot}
                              {...mapCoordsToCircleProps(hotspot.coords)} />
                          );
                        case 'poly':
                          return (
                            <polygon
                              key={hotspot.guid}
                              className={classes.hotspot}
                              {...mapCoordsToPolygonProps(hotspot.coords)} />
                          );
                        default:
                          return null;
                      }
                    })}
                </svg>
              </div>
            )
            : (
              <div className={classes.noImage} />
            )
          }
        </div>
      </div>
    );
  }
}
