// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function valueOr(opt, $$default) {
  if (opt) {
    return opt[0];
  } else {
    return $$default;
  }
}

function valueOrCompute(opt, fn) {
  if (opt) {
    return opt[0];
  } else {
    return Curry._1(fn, /* () */0);
  }
}

function valueOrThrow(opt) {
  if (opt) {
    return opt[0];
  } else {
    throw Caml_builtin_exceptions.not_found;
  }
}

function lift(opt, fn) {
  if (opt) {
    return Curry._1(fn, opt[0]);
  } else {
    return opt;
  }
}

exports.valueOr = valueOr;
exports.valueOrCompute = valueOrCompute;
exports.valueOrThrow = valueOrThrow;
exports.lift = lift;
/* No side effect */
