// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function valueOr(opt, $$default) {
  if (opt) {
    return opt[0];
  } else {
    return $$default;
  }
}

function valueOrCompute(opt, fn) {
  if (opt) {
    return opt[0];
  } else {
    return Curry._1(fn, /* () */0);
  }
}

function lift(opt, fn) {
  if (opt) {
    return Curry._1(fn, opt[0]);
  } else {
    return opt;
  }
}

exports.valueOr = valueOr;
exports.valueOrCompute = valueOrCompute;
exports.lift = lift;
/* No side effect */
