// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Jss = require("styles/jss");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Option$CourseEditor = require("../../utils/reason/Option.bs.js");

function classNames(names) {
  return List.fold_left((function (a, b) {
                return a + (" " + b);
              }), "", List.filter((function (name) {
                      return name !== "";
                    }))(names));
}

function jssClass(classes, name) {
  return Option$CourseEditor.valueOr(Js_primitive.undefined_to_opt(classes[name]), "");
}

function injectSheet(prim, prim$1) {
  return Jss.injectSheetRE(prim, prim$1);
}

exports.classNames = classNames;
exports.jssClass = jssClass;
exports.injectSheet = injectSheet;
/* styles/jss Not a pure module */
