name: CI

on:
  push:
    branches:
      - master
      - 'SPRINT-*'
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:8

    steps:
      - uses: actions/checkout@v1
      - name: Install & Tests
        run: |
          npm install
          npm run build
